package gui;

import actions.Action;
import actions.ActionSet;
import client.Sender;
import javax.swing.SpinnerNumberModel;
import model.Game;

/**
 * Pannello per le puntate
 */
public class AmountPanel extends GamePanel {

    /**
     * Crea un nuovo AmountPanel
     * @param game il gioco su cui è definito
     */
    public AmountPanel(Game game) {
        super(game);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        amountSpinner = new javax.swing.JSpinner();
        okButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(amountSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(okButton)
                        .addComponent(resetButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed

        int amount = (int)amountSpinner.getValue();
        selectedAction.setAmount(amount);
        if(selectedAction!=null)
        {
            //System.out.println(JSONEncoder.getInstance().encodeAct(selectedAction));
            Sender.getInstance().sendAction(selectedAction);
        }
        selectedAction = null;
        firePropertyChange("ACTION_SENT", null, selectedAction);
    }//GEN-LAST:event_okButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        SpinnerNumberModel model = (SpinnerNumberModel)amountSpinner.getModel();
        amountSpinner.setValue(model.getMinimum());
    }//GEN-LAST:event_resetButtonActionPerformed

    public void act(Action defaultAction)
    {
        int max = 0;
        int min = game.getMinBet();
        this.selectedAction = defaultAction;
        okButton.setText(defaultAction.getName());
        if (selectedAction.getActionType() == ActionSet.BET)
        {
            max = game.getCurrentPlayer().getStake();
        }
        if (selectedAction.getActionType() == ActionSet.RAISE)
        {
            max = game.getCurrentPlayer().getStake() + game.getCurrentPlayer().getCurrentBet() - game.getBet();
        }
        if (max < min)
        {
            min = max;
        }
        amountSpinner.setModel(new SpinnerNumberModel(min, min, max, game.getSettings().getBigBlind()));
        amountSpinner.setValue(game.getMinBet());
    }
    
    public int getAmount() {
        return (int)amountSpinner.getValue();
    }
    
   
    

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner amountSpinner;
    private javax.swing.JButton okButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables
    private Action defaultAction;
    private Action selectedAction;
    private final Object lock = new Object();
}
