/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 */
public class InterfacciaPoker extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public InterfacciaPoker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoardPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CartaB1 = new javax.swing.JLabel();
        CartaB3 = new javax.swing.JLabel();
        CartaB2 = new javax.swing.JLabel();
        CartaB4 = new javax.swing.JLabel();
        CartaB5 = new javax.swing.JLabel();
        PlayerPanel = new javax.swing.JPanel();
        PannelloPulsanti = new javax.swing.JPanel();
        Check_Call = new javax.swing.JButton();
        Raise = new javax.swing.JButton();
        Fold = new javax.swing.JButton();
        Carta2 = new javax.swing.JLabel();
        Carta1 = new javax.swing.JLabel();
        NomeGiocatore = new javax.swing.JLabel();
        StakeGiocatore = new javax.swing.JLabel();
        PuntataPanel = new javax.swing.JLabel();
        PlayerPanel2 = new javax.swing.JPanel();
        Carta2_2 = new javax.swing.JLabel();
        Carta2_1 = new javax.swing.JLabel();
        NomeGiocatore2 = new javax.swing.JLabel();
        StakeGiocatore2 = new javax.swing.JLabel();
        PuntataPanel2 = new javax.swing.JLabel();
        PlayerPanel4 = new javax.swing.JPanel();
        Carta1_3 = new javax.swing.JLabel();
        Carta1_4 = new javax.swing.JLabel();
        NomeGiocatore3 = new javax.swing.JLabel();
        StakeGiocatore3 = new javax.swing.JLabel();
        PuntataPanel3 = new javax.swing.JLabel();
        PlayerPanel5 = new javax.swing.JPanel();
        Carta1_5 = new javax.swing.JLabel();
        Carta1_6 = new javax.swing.JLabel();
        NomeGiocatore4 = new javax.swing.JLabel();
        StakeGiocatore4 = new javax.swing.JLabel();
        PuntataPanel4 = new javax.swing.JLabel();
        PlayerPanel6 = new javax.swing.JPanel();
        Carta1_7 = new javax.swing.JLabel();
        Carta1_8 = new javax.swing.JLabel();
        NomeGiocatore5 = new javax.swing.JLabel();
        StakeGiocatore5 = new javax.swing.JLabel();
        PuntataPanel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BoardPanel.setBackground(new java.awt.Color(14, 133, 70));

        jLabel1.setText("BANCO");

        CartaB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaB1.setText("CartaBanco1");

        CartaB3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaB3.setText("CartaBanco3");

        CartaB2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaB2.setText("Cartabanco2");

        CartaB4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaB4.setText("CartaBanco4");

        CartaB5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CartaB5.setText("CartaBanco5");

        javax.swing.GroupLayout BoardPanelLayout = new javax.swing.GroupLayout(BoardPanel);
        BoardPanel.setLayout(BoardPanelLayout);
        BoardPanelLayout.setHorizontalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardPanelLayout.createSequentialGroup()
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BoardPanelLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addComponent(jLabel1))
                    .addGroup(BoardPanelLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(CartaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CartaB2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CartaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CartaB4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CartaB5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BoardPanelLayout.setVerticalGroup(
            BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BoardPanelLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BoardPanelLayout.createSequentialGroup()
                .addContainerGap(66, Short.MAX_VALUE)
                .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CartaB5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CartaB4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CartaB3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BoardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CartaB1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(CartaB2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        PlayerPanel.setBackground(new java.awt.Color(14, 133, 70));

        PannelloPulsanti.setBackground(new java.awt.Color(14, 133, 70));

        Check_Call.setText("Check/Call");

        Raise.setText("Raise");

        Fold.setText("Fold");
        Fold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FoldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelloPulsantiLayout = new javax.swing.GroupLayout(PannelloPulsanti);
        PannelloPulsanti.setLayout(PannelloPulsantiLayout);
        PannelloPulsantiLayout.setHorizontalGroup(
            PannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloPulsantiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Check_Call)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Raise)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Fold)
                .addGap(34, 34, 34))
        );
        PannelloPulsantiLayout.setVerticalGroup(
            PannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloPulsantiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Check_Call)
                    .addComponent(Raise)
                    .addComponent(Fold)))
        );

        Carta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta2.setText("SpazioCarta2");

        Carta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1.setText("SpazioCarta1");

        NomeGiocatore.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NomeGiocatore.setForeground(new java.awt.Color(151, 161, 24));
        NomeGiocatore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeGiocatore.setText("NomeGiocatore");

        StakeGiocatore.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        StakeGiocatore.setForeground(new java.awt.Color(151, 161, 24));
        StakeGiocatore.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StakeGiocatore.setText("Stake attuale");

        PuntataPanel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PuntataPanel.setForeground(new java.awt.Color(151, 161, 24));
        PuntataPanel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuntataPanel.setText("Scelta/puntata");

        javax.swing.GroupLayout PlayerPanelLayout = new javax.swing.GroupLayout(PlayerPanel);
        PlayerPanel.setLayout(PlayerPanelLayout);
        PlayerPanelLayout.setHorizontalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StakeGiocatore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeGiocatore, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanelLayout.createSequentialGroup()
                        .addGroup(PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PannelloPulsanti, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PlayerPanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(Carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(PuntataPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlayerPanelLayout.setVerticalGroup(
            PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeGiocatore, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StakeGiocatore)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PuntataPanel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PannelloPulsanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        PlayerPanel2.setBackground(new java.awt.Color(14, 133, 70));

        Carta2_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta2_2.setText("SpazioCarta2");

        Carta2_1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta2_1.setText("SpazioCarta1");

        NomeGiocatore2.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NomeGiocatore2.setForeground(new java.awt.Color(151, 161, 24));
        NomeGiocatore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeGiocatore2.setText("NomeGiocatore");

        StakeGiocatore2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        StakeGiocatore2.setForeground(new java.awt.Color(151, 161, 24));
        StakeGiocatore2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StakeGiocatore2.setText("Stake attuale");

        PuntataPanel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PuntataPanel2.setForeground(new java.awt.Color(151, 161, 24));
        PuntataPanel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuntataPanel2.setText("Scelta/puntata");

        javax.swing.GroupLayout PlayerPanel2Layout = new javax.swing.GroupLayout(PlayerPanel2);
        PlayerPanel2.setLayout(PlayerPanel2Layout);
        PlayerPanel2Layout.setHorizontalGroup(
            PlayerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PlayerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StakeGiocatore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeGiocatore2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Carta2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Carta2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(PuntataPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlayerPanel2Layout.setVerticalGroup(
            PlayerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeGiocatore2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StakeGiocatore2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PuntataPanel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta2_1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta2_2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        PlayerPanel4.setBackground(new java.awt.Color(14, 133, 70));

        Carta1_3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_3.setText("SpazioCarta2");

        Carta1_4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_4.setText("SpazioCarta1");

        NomeGiocatore3.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NomeGiocatore3.setForeground(new java.awt.Color(151, 161, 24));
        NomeGiocatore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeGiocatore3.setText("NomeGiocatore");

        StakeGiocatore3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        StakeGiocatore3.setForeground(new java.awt.Color(151, 161, 24));
        StakeGiocatore3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StakeGiocatore3.setText("Stake attuale");

        PuntataPanel3.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PuntataPanel3.setForeground(new java.awt.Color(151, 161, 24));
        PuntataPanel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuntataPanel3.setText("Scelta/puntata");

        javax.swing.GroupLayout PlayerPanel4Layout = new javax.swing.GroupLayout(PlayerPanel4);
        PlayerPanel4.setLayout(PlayerPanel4Layout);
        PlayerPanel4Layout.setHorizontalGroup(
            PlayerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PlayerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StakeGiocatore3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeGiocatore3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Carta1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Carta1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(PuntataPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlayerPanel4Layout.setVerticalGroup(
            PlayerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeGiocatore3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StakeGiocatore3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PuntataPanel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta1_4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta1_3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        PlayerPanel5.setBackground(new java.awt.Color(14, 133, 70));

        Carta1_5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_5.setText("SpazioCarta2");

        Carta1_6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_6.setText("SpazioCarta1");

        NomeGiocatore4.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NomeGiocatore4.setForeground(new java.awt.Color(151, 161, 24));
        NomeGiocatore4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeGiocatore4.setText("NomeGiocatore");

        StakeGiocatore4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        StakeGiocatore4.setForeground(new java.awt.Color(151, 161, 24));
        StakeGiocatore4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StakeGiocatore4.setText("Stake attuale");

        PuntataPanel4.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PuntataPanel4.setForeground(new java.awt.Color(151, 161, 24));
        PuntataPanel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuntataPanel4.setText("Scelta/puntata");

        javax.swing.GroupLayout PlayerPanel5Layout = new javax.swing.GroupLayout(PlayerPanel5);
        PlayerPanel5.setLayout(PlayerPanel5Layout);
        PlayerPanel5Layout.setHorizontalGroup(
            PlayerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PlayerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StakeGiocatore4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeGiocatore4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanel5Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Carta1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Carta1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(PuntataPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlayerPanel5Layout.setVerticalGroup(
            PlayerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeGiocatore4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StakeGiocatore4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PuntataPanel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta1_6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta1_5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        PlayerPanel6.setBackground(new java.awt.Color(14, 133, 70));

        Carta1_7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_7.setText("SpazioCarta2");

        Carta1_8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Carta1_8.setText("SpazioCarta1");

        NomeGiocatore5.setFont(new java.awt.Font("Ubuntu", 1, 20)); // NOI18N
        NomeGiocatore5.setForeground(new java.awt.Color(151, 161, 24));
        NomeGiocatore5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NomeGiocatore5.setText("NomeGiocatore");

        StakeGiocatore5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        StakeGiocatore5.setForeground(new java.awt.Color(151, 161, 24));
        StakeGiocatore5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        StakeGiocatore5.setText("Stake attuale");

        PuntataPanel5.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        PuntataPanel5.setForeground(new java.awt.Color(151, 161, 24));
        PuntataPanel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PuntataPanel5.setText("Scelta/puntata");

        javax.swing.GroupLayout PlayerPanel6Layout = new javax.swing.GroupLayout(PlayerPanel6);
        PlayerPanel6.setLayout(PlayerPanel6Layout);
        PlayerPanel6Layout.setHorizontalGroup(
            PlayerPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel6Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(PlayerPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(StakeGiocatore5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(NomeGiocatore5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PlayerPanel6Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Carta1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Carta1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addComponent(PuntataPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PlayerPanel6Layout.setVerticalGroup(
            PlayerPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PlayerPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(NomeGiocatore5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StakeGiocatore5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(PuntataPanel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PlayerPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Carta1_8, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Carta1_7, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PlayerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(PlayerPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(PlayerPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(PlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(152, 152, 152)))
                .addComponent(PlayerPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PlayerPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PlayerPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(PlayerPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BoardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PlayerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(PlayerPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FoldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FoldActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JLabel Carta1;
    private javax.swing.JLabel Carta1_3;
    private javax.swing.JLabel Carta1_4;
    private javax.swing.JLabel Carta1_5;
    private javax.swing.JLabel Carta1_6;
    private javax.swing.JLabel Carta1_7;
    private javax.swing.JLabel Carta1_8;
    private javax.swing.JLabel Carta2;
    private javax.swing.JLabel Carta2_1;
    private javax.swing.JLabel Carta2_2;
    private javax.swing.JLabel CartaB1;
    private javax.swing.JLabel CartaB2;
    private javax.swing.JLabel CartaB3;
    private javax.swing.JLabel CartaB4;
    private javax.swing.JLabel CartaB5;
    private javax.swing.JButton Check_Call;
    private javax.swing.JButton Check_Call3;
    private javax.swing.JButton Fold;
    private javax.swing.JButton Fold3;
    private javax.swing.JLabel NomeGiocatore;
    private javax.swing.JLabel NomeGiocatore2;
    private javax.swing.JLabel NomeGiocatore3;
    private javax.swing.JLabel NomeGiocatore4;
    private javax.swing.JLabel NomeGiocatore5;
    private javax.swing.JPanel PannelloPulsanti;
    private javax.swing.JPanel PannelloPulsanti3;
    private javax.swing.JPanel PlayerPanel;
    private javax.swing.JPanel PlayerPanel2;
    private javax.swing.JPanel PlayerPanel3;
    private javax.swing.JPanel PlayerPanel4;
    private javax.swing.JPanel PlayerPanel5;
    private javax.swing.JPanel PlayerPanel6;
    private javax.swing.JLabel PuntataPanel;
    private javax.swing.JLabel PuntataPanel2;
    private javax.swing.JLabel PuntataPanel3;
    private javax.swing.JLabel PuntataPanel4;
    private javax.swing.JLabel PuntataPanel5;
    private javax.swing.JButton Raise;
    private javax.swing.JButton Raise3;
    private javax.swing.JLabel StakeGiocatore;
    private javax.swing.JLabel StakeGiocatore2;
    private javax.swing.JLabel StakeGiocatore3;
    private javax.swing.JLabel StakeGiocatore4;
    private javax.swing.JLabel StakeGiocatore5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
