/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 * GUI per la partita di Poker
 */
public class InterfacciaPoker extends javax.swing.JFrame {

    /**
     * Creates new form InterfacciaPoker
     */
    public InterfacciaPoker() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sfondoFrame = new javax.swing.JPanel();
        boardPanel = new javax.swing.JPanel();
        cartaBoard1 = new javax.swing.JLabel();
        cartaBoard4 = new javax.swing.JLabel();
        cartaBoard2 = new javax.swing.JLabel();
        cartaBoard5 = new javax.swing.JLabel();
        cartaBoard3 = new javax.swing.JLabel();
        potLabel = new javax.swing.JLabel();
        turnoLabel = new javax.swing.JLabel();
        playerPanel = new javax.swing.JPanel();
        pannelloPulsanti = new javax.swing.JPanel();
        callButton = new javax.swing.JButton();
        raiseButton = new javax.swing.JButton();
        foldButton = new javax.swing.JButton();
        carta2Player = new javax.swing.JLabel();
        nomePlayer = new javax.swing.JLabel();
        stakePlayer = new javax.swing.JLabel();
        azionePlayer = new javax.swing.JLabel();
        carta1Player = new javax.swing.JLabel();
        dealerPlayer = new javax.swing.JLabel();
        pannelloRaise = new javax.swing.JPanel();
        okButton = new javax.swing.JButton();
        raiseSpinner = new javax.swing.JSpinner();
        player1Panel = new javax.swing.JPanel();
        carta2Player1 = new javax.swing.JLabel();
        nomePlayer1 = new javax.swing.JLabel();
        stakePlayer1 = new javax.swing.JLabel();
        azionePlayer1 = new javax.swing.JLabel();
        carta1Player1 = new javax.swing.JLabel();
        dealerPlayer1 = new javax.swing.JLabel();
        player2Panel = new javax.swing.JPanel();
        carta2Player2 = new javax.swing.JLabel();
        nomePlayer2 = new javax.swing.JLabel();
        stakePlayer2 = new javax.swing.JLabel();
        azionePlayer2 = new javax.swing.JLabel();
        carta1Player2 = new javax.swing.JLabel();
        dealerPlayer2 = new javax.swing.JLabel();
        player3Panel = new javax.swing.JPanel();
        carta2Player3 = new javax.swing.JLabel();
        nomePlayer3 = new javax.swing.JLabel();
        stakePlayer3 = new javax.swing.JLabel();
        azionePlayer3 = new javax.swing.JLabel();
        carta1Player3 = new javax.swing.JLabel();
        dealerPlayer3 = new javax.swing.JLabel();
        player4Panel = new javax.swing.JPanel();
        carta2Player4 = new javax.swing.JLabel();
        nomePlayer4 = new javax.swing.JLabel();
        stakePlayer4 = new javax.swing.JLabel();
        azionePlayer4 = new javax.swing.JLabel();
        carta1Player4 = new javax.swing.JLabel();
        dealerPlayer4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Poker");
        setAutoRequestFocus(false);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setPreferredSize(new java.awt.Dimension(1200, 700));
        setResizable(false);

        sfondoFrame.setBackground(new java.awt.Color(0, 102, 51));
        sfondoFrame.setPreferredSize(new java.awt.Dimension(1200, 700));

        boardPanel.setBackground(new java.awt.Color(0, 102, 51));
        boardPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        cartaBoard1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaBoard1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cartaBoard4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaBoard4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cartaBoard2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaBoard2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cartaBoard5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaBoard5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        cartaBoard3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cartaBoard3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        potLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        potLabel.setForeground(new java.awt.Color(177, 177, 4));
        potLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        potLabel.setText("Pot");
        potLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        turnoLabel.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        turnoLabel.setForeground(new java.awt.Color(177, 177, 4));
        turnoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turnoLabel.setText("Turno");
        turnoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));
        turnoLabel.setMaximumSize(new java.awt.Dimension(26, 20));
        turnoLabel.setMinimumSize(new java.awt.Dimension(26, 20));
        turnoLabel.setPreferredSize(new java.awt.Dimension(26, 20));

        javax.swing.GroupLayout boardPanelLayout = new javax.swing.GroupLayout(boardPanel);
        boardPanel.setLayout(boardPanelLayout);
        boardPanelLayout.setHorizontalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(boardPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(boardPanelLayout.createSequentialGroup()
                        .addComponent(cartaBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cartaBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(boardPanelLayout.createSequentialGroup()
                        .addComponent(turnoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(potLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        boardPanelLayout.setVerticalGroup(
            boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, boardPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turnoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                    .addComponent(potLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(boardPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cartaBoard3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaBoard5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaBoard4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaBoard2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cartaBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        playerPanel.setBackground(new java.awt.Color(0, 102, 51));
        playerPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        pannelloPulsanti.setBackground(new java.awt.Color(0, 102, 51));

        callButton.setBackground(new java.awt.Color(204, 255, 255));
        callButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        callButton.setText("Call");
        callButton.setPreferredSize(new java.awt.Dimension(70, 20));
        callButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callButtonActionPerformed(evt);
            }
        });

        raiseButton.setBackground(new java.awt.Color(204, 255, 255));
        raiseButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        raiseButton.setText("Raise");
        raiseButton.setPreferredSize(new java.awt.Dimension(70, 20));

        foldButton.setBackground(new java.awt.Color(204, 255, 255));
        foldButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        foldButton.setText("Fold");
        foldButton.setPreferredSize(new java.awt.Dimension(70, 20));
        foldButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foldButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pannelloPulsantiLayout = new javax.swing.GroupLayout(pannelloPulsanti);
        pannelloPulsanti.setLayout(pannelloPulsantiLayout);
        pannelloPulsantiLayout.setHorizontalGroup(
            pannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloPulsantiLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(callButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(raiseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(foldButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pannelloPulsantiLayout.setVerticalGroup(
            pannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloPulsantiLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(pannelloPulsantiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(raiseButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(callButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(foldButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        carta2Player.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2Player.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nomePlayer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomePlayer.setForeground(new java.awt.Color(177, 177, 4));
        nomePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePlayer.setText("NomeGiocatore");
        nomePlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        stakePlayer.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        stakePlayer.setForeground(new java.awt.Color(177, 177, 4));
        stakePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stakePlayer.setText("Stake");
        stakePlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        azionePlayer.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        azionePlayer.setForeground(new java.awt.Color(177, 177, 4));
        azionePlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azionePlayer.setText("Azione");
        azionePlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        carta1Player.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1Player.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dealerPlayer.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dealerPlayer.setForeground(new java.awt.Color(102, 0, 0));
        dealerPlayer.setText("D");
        dealerPlayer.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        pannelloRaise.setBackground(new java.awt.Color(0, 102, 51));

        okButton.setBackground(new java.awt.Color(204, 255, 255));
        okButton.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        okButton.setText("OK");
        okButton.setMaximumSize(new java.awt.Dimension(57, 23));
        okButton.setMinimumSize(new java.awt.Dimension(57, 23));
        okButton.setPreferredSize(new java.awt.Dimension(70, 20));

        raiseSpinner.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        raiseSpinner.setMinimumSize(new java.awt.Dimension(73, 22));

        javax.swing.GroupLayout pannelloRaiseLayout = new javax.swing.GroupLayout(pannelloRaise);
        pannelloRaise.setLayout(pannelloRaiseLayout);
        pannelloRaiseLayout.setHorizontalGroup(
            pannelloRaiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloRaiseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(raiseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        pannelloRaiseLayout.setVerticalGroup(
            pannelloRaiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pannelloRaiseLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pannelloRaiseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(raiseSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout playerPanelLayout = new javax.swing.GroupLayout(playerPanel);
        playerPanel.setLayout(playerPanelLayout);
        playerPanelLayout.setHorizontalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azionePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomePlayer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carta1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2Player, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPlayer)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(pannelloPulsanti, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(stakePlayer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pannelloRaise, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        playerPanelLayout.setVerticalGroup(
            playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stakePlayer)
                .addGap(4, 4, 4)
                .addComponent(azionePlayer)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(playerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta1Player, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2Player, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerPlayer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pannelloPulsanti, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(pannelloRaise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2))
        );

        player1Panel.setBackground(new java.awt.Color(0, 102, 51));
        player1Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        carta2Player1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2Player1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nomePlayer1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomePlayer1.setForeground(new java.awt.Color(177, 177, 4));
        nomePlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePlayer1.setText("NomeGiocatore1");
        nomePlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        stakePlayer1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        stakePlayer1.setForeground(new java.awt.Color(177, 177, 4));
        stakePlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stakePlayer1.setText("Stake");
        stakePlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        azionePlayer1.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        azionePlayer1.setForeground(new java.awt.Color(177, 177, 4));
        azionePlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azionePlayer1.setText("Azione");
        azionePlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        carta1Player1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1Player1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dealerPlayer1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dealerPlayer1.setForeground(new java.awt.Color(102, 0, 0));
        dealerPlayer1.setText("D");
        dealerPlayer1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout player1PanelLayout = new javax.swing.GroupLayout(player1Panel);
        player1Panel.setLayout(player1PanelLayout);
        player1PanelLayout.setHorizontalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azionePlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomePlayer1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carta1Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPlayer1)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(stakePlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        player1PanelLayout.setVerticalGroup(
            player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player1PanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stakePlayer1)
                .addGap(4, 4, 4)
                .addComponent(azionePlayer1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta1Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2Player1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerPlayer1))
                .addContainerGap())
        );

        player2Panel.setBackground(new java.awt.Color(0, 102, 51));
        player2Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        carta2Player2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2Player2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nomePlayer2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomePlayer2.setForeground(new java.awt.Color(177, 177, 4));
        nomePlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePlayer2.setText("NomeGiocatore2");
        nomePlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        stakePlayer2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        stakePlayer2.setForeground(new java.awt.Color(177, 177, 4));
        stakePlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stakePlayer2.setText("Stake");
        stakePlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        azionePlayer2.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        azionePlayer2.setForeground(new java.awt.Color(177, 177, 4));
        azionePlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azionePlayer2.setText("Azione");
        azionePlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        carta1Player2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1Player2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dealerPlayer2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dealerPlayer2.setForeground(new java.awt.Color(102, 0, 0));
        dealerPlayer2.setText("D");
        dealerPlayer2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout player2PanelLayout = new javax.swing.GroupLayout(player2Panel);
        player2Panel.setLayout(player2PanelLayout);
        player2PanelLayout.setHorizontalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azionePlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomePlayer2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carta1Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPlayer2)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(stakePlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        player2PanelLayout.setVerticalGroup(
            player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player2PanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stakePlayer2)
                .addGap(4, 4, 4)
                .addComponent(azionePlayer2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player2PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta1Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2Player2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerPlayer2))
                .addContainerGap())
        );

        player3Panel.setBackground(new java.awt.Color(0, 102, 51));
        player3Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        carta2Player3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2Player3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nomePlayer3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomePlayer3.setForeground(new java.awt.Color(177, 177, 4));
        nomePlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePlayer3.setText("NomeGiocatore3");
        nomePlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        stakePlayer3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        stakePlayer3.setForeground(new java.awt.Color(177, 177, 4));
        stakePlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stakePlayer3.setText("Stake");
        stakePlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        azionePlayer3.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        azionePlayer3.setForeground(new java.awt.Color(177, 177, 4));
        azionePlayer3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azionePlayer3.setText("Azione");
        azionePlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        carta1Player3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1Player3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dealerPlayer3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dealerPlayer3.setForeground(new java.awt.Color(102, 0, 0));
        dealerPlayer3.setText("D");
        dealerPlayer3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout player3PanelLayout = new javax.swing.GroupLayout(player3Panel);
        player3Panel.setLayout(player3PanelLayout);
        player3PanelLayout.setHorizontalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azionePlayer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomePlayer3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player3PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carta1Player3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2Player3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPlayer3)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(stakePlayer3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        player3PanelLayout.setVerticalGroup(
            player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player3PanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePlayer3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stakePlayer3)
                .addGap(4, 4, 4)
                .addComponent(azionePlayer3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player3PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta1Player3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2Player3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerPlayer3))
                .addContainerGap())
        );

        player4Panel.setBackground(new java.awt.Color(0, 102, 51));
        player4Panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 0), 3));

        carta2Player4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta2Player4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        nomePlayer4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        nomePlayer4.setForeground(new java.awt.Color(177, 177, 4));
        nomePlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nomePlayer4.setText("NomeGiocatore4");
        nomePlayer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        stakePlayer4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        stakePlayer4.setForeground(new java.awt.Color(177, 177, 4));
        stakePlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        stakePlayer4.setText("Stake");
        stakePlayer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        azionePlayer4.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        azionePlayer4.setForeground(new java.awt.Color(177, 177, 4));
        azionePlayer4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        azionePlayer4.setText("Azione");
        azionePlayer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 51)));

        carta1Player4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        carta1Player4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        dealerPlayer4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        dealerPlayer4.setForeground(new java.awt.Color(102, 0, 0));
        dealerPlayer4.setText("D");
        dealerPlayer4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0)));

        javax.swing.GroupLayout player4PanelLayout = new javax.swing.GroupLayout(player4Panel);
        player4Panel.setLayout(player4PanelLayout);
        player4PanelLayout.setHorizontalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(azionePlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(nomePlayer4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(player4PanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(carta1Player4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carta2Player4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dealerPlayer4)
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(stakePlayer4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        player4PanelLayout.setVerticalGroup(
            player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(player4PanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(nomePlayer4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(stakePlayer4)
                .addGap(4, 4, 4)
                .addComponent(azionePlayer4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(player4PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(carta1Player4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carta2Player4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dealerPlayer4))
                .addContainerGap())
        );

        javax.swing.GroupLayout sfondoFrameLayout = new javax.swing.GroupLayout(sfondoFrame);
        sfondoFrame.setLayout(sfondoFrameLayout);
        sfondoFrameLayout.setHorizontalGroup(
            sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoFrameLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(player4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoFrameLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoFrameLayout.createSequentialGroup()
                                .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(177, 177, 177))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoFrameLayout.createSequentialGroup()
                                .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41))))
                    .addGroup(sfondoFrameLayout.createSequentialGroup()
                        .addComponent(player3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        sfondoFrameLayout.setVerticalGroup(
            sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoFrameLayout.createSequentialGroup()
                .addGroup(sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoFrameLayout.createSequentialGroup()
                        .addGroup(sfondoFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(player2Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(player3Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(boardPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(playerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sfondoFrameLayout.createSequentialGroup()
                        .addGap(208, 208, 208)
                        .addComponent(player1Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sfondoFrameLayout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(player4Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondoFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 1220, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(sfondoFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void callButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_callButtonActionPerformed

    private void foldButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foldButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foldButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        InterfacciaPoker prova = new InterfacciaPoker();
        prova.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel azionePlayer;
    private javax.swing.JLabel azionePlayer1;
    private javax.swing.JLabel azionePlayer2;
    private javax.swing.JLabel azionePlayer3;
    private javax.swing.JLabel azionePlayer4;
    private javax.swing.JPanel boardPanel;
    private javax.swing.JButton callButton;
    private javax.swing.JLabel carta1Player;
    private javax.swing.JLabel carta1Player1;
    private javax.swing.JLabel carta1Player2;
    private javax.swing.JLabel carta1Player3;
    private javax.swing.JLabel carta1Player4;
    private javax.swing.JLabel carta2Player;
    private javax.swing.JLabel carta2Player1;
    private javax.swing.JLabel carta2Player2;
    private javax.swing.JLabel carta2Player3;
    private javax.swing.JLabel carta2Player4;
    private javax.swing.JLabel cartaBoard1;
    private javax.swing.JLabel cartaBoard2;
    private javax.swing.JLabel cartaBoard3;
    private javax.swing.JLabel cartaBoard4;
    private javax.swing.JLabel cartaBoard5;
    private javax.swing.JLabel dealerPlayer;
    private javax.swing.JLabel dealerPlayer1;
    private javax.swing.JLabel dealerPlayer2;
    private javax.swing.JLabel dealerPlayer3;
    private javax.swing.JLabel dealerPlayer4;
    private javax.swing.JButton foldButton;
    private javax.swing.JLabel nomePlayer;
    private javax.swing.JLabel nomePlayer1;
    private javax.swing.JLabel nomePlayer2;
    private javax.swing.JLabel nomePlayer3;
    private javax.swing.JLabel nomePlayer4;
    private javax.swing.JButton okButton;
    private javax.swing.JPanel pannelloPulsanti;
    private javax.swing.JPanel pannelloRaise;
    private javax.swing.JPanel player1Panel;
    private javax.swing.JPanel player2Panel;
    private javax.swing.JPanel player3Panel;
    private javax.swing.JPanel player4Panel;
    private javax.swing.JPanel playerPanel;
    private javax.swing.JLabel potLabel;
    private javax.swing.JButton raiseButton;
    private javax.swing.JSpinner raiseSpinner;
    private javax.swing.JPanel sfondoFrame;
    private javax.swing.JLabel stakePlayer;
    private javax.swing.JLabel stakePlayer1;
    private javax.swing.JLabel stakePlayer2;
    private javax.swing.JLabel stakePlayer3;
    private javax.swing.JLabel stakePlayer4;
    private javax.swing.JLabel turnoLabel;
    // End of variables declaration//GEN-END:variables
}
